const mongoose = require("mongoose");

// A customer's saved address book. Lives as a subdocument array on the
// user, each entry gets its own real _id automatically.
const addressSchema = new mongoose.Schema(
    {
        label: {
            type: String,
            enum: ["Home", "Work", "Other"],
            default: "Home",
        },
        recipientName: {
            type: String,
            required: true,
            trim: true,
        },
        flat: {
            type: String,
            required: true,
            trim: true,
        },
        area: {
            type: String,
            required: true,
            trim: true,
        },
        city: {
            type: String,
            required: true,
            trim: true,
        },
        state: {
            type: String,
            required: true,
            trim: true,
        },
        pincode: {
            type: String,
            required: true,
            match: [/^[0-9]{6}$/, "Please provide a valid 6-digit pincode"],
        },
        phone: {
            type: String,
            required: true,
            match: [/^[0-9]{10}$/, "Please provide a valid 10-digit phone number"],
        },
        isDefault: {
            type: Boolean,
            default: false,
        },
    },
    { timestamps: true }
);

// ───────────── NEW: SAVED PAYMENT METHODS ─────────────
// Stores Razorpay token references, completely keeping the app and 
// server out of PCI-DSS scope by never storing raw card numbers.
const paymentMethodSchema = new mongoose.Schema(
    {
        type: {
            type: String,
            enum: ["card", "upi"],
            required: true,
        },
        // The token reference generated by Razorpay
        razorpayTokenId: {
            type: String,
            required: true,
        },
        // --- Card-specific display fields ---
        network: { type: String }, // e.g., "Visa", "MasterCard"
        last4: { type: String },
        expiryMonth: { type: Number },
        expiryYear: { type: Number },
        
        // --- UPI-specific display fields ---
        vpa: { type: String }, // e.g., "name@okhdfcbank"
        
        isDefault: {
            type: Boolean,
            default: false,
        },
    },
    { timestamps: true }
);

// Customer accounts, phone + OTP only, no password. Created automatically
// the first time a phone number successfully verifies an OTP.
const userSchema = new mongoose.Schema(
    {
        phone: {
            type: String,
            required: true,
            unique: true,
            index: true,
            match: [/^[0-9]{10}$/, "Please provide a valid 10-digit phone number"],
        },
        name: {
            type: String,
            trim: true,
        },
        addresses: [addressSchema],
        paymentMethods: [paymentMethodSchema], // <-- Added array here
    },
    { timestamps: true }
);

module.exports = mongoose.model("User", userSchema);